# Generated by Django 4.2.7 on 2023-11-01 13:59

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_x', models.FloatField()),
                ('player_y', models.FloatField()),
                ('player_scene', models.TextField()),
                ('player_health', models.PositiveIntegerField(validators=[api.models.validate_positive_health])),
                ('player_laser_bullets', models.IntegerField()),
                ('player_grenade_bullets', models.IntegerField()),
                ('player_max_score', models.IntegerField()),
            ],
        ),
    ]
